name: Run E2E Automation

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      service:
        required: true
        type: string

permissions:
  contents: read
  packages: read
  deployments: read

jobs:
  e2e:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/playwright-test:sha-${{ github.sha }}
      env:
        CI: "true"
        TZ: Asia/Bangkok

    defaults:
      run:
        shell: bash
        working-directory: /app

    strategy:
      fail-fast: false
      matrix:
        project: ["Chromium Desktop", "Safari Mobile"]

    steps:
      - name: Resolve service → URL + tag
        id: target
        run: |
          svc='${{ inputs.service }}'
          case "$svc" in
            community-member|cm) url='https://v0-cmlookup2.vercel.app/'; grep='@cm' ;;
            earnin|ei)           url='https://www.earnin.com/financial-calculators'; grep='@earnin' ;;
            *) echo "Unknown service: $svc"; exit 1 ;;
          esac
          echo "url=$url"   >> $GITHUB_OUTPUT
          echo "grep=$grep" >> $GITHUB_OUTPUT
          echo "SERVICE=$svc / URL=$url / GREP=$grep"

      - name: Wait target ready
        continue-on-error: true
        run: |
          url='${{ steps.target.outputs.url }}'
          npx wait-on --timeout=240000 "$url" || true

      - name: Run Playwright (${{ matrix.project }})
        env:
          BASE_URL: ${{ steps.target.outputs.url }}
        run: |
          npx playwright test \
            --grep "${{ steps.target.outputs.grep }}" \
            --project="${{ matrix.project }}" \
            --reporter=github,html,junit

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.project }}
          path: /app/playwright-report
          retention-days: 7

      - name: Upload traces/screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.project }}
          path: |
            /app/test-results/**
            /app/playwright-report/**
          retention-days: 7
